name: Link to Trello

on:
  pull_request:
    types: [ "opened", "edited" ]

jobs:
  trello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Test secrets
        run: |
          test -n "{{ secrets.TRELLO_KEY }}"
          test -n "{{ secrets.TRELLO_TOKEN }}"
      - name: Attach PR to trello cards
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
          TRELLO_KEY: ${{ secrets.TRELLO_KEY }}
          TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
        run: ./main.sh "$GITHUB_EVENT"

